using CiphersMain.Breakers.Substitution;
using CiphersMain.Breakers;
using CiphersMain.Ciphers;
using CiphersMain.Keys;
using ErikCommon;
using FrequencyAnalysis.Data;
using System.Diagnostics;
using CiphersMain.Breakers.Vignere;

string outputPath = @".\Output\test2.json";

// Load example texts
string path = @".\ExampleText.txt";
List<string> texts = new List<string>{ };

if (File.Exists(path))
    texts.Add(Utilities.CipherFormat(File.ReadAllText(path).Substring(0,1600)));
texts.Add(Utilities.CipherFormat(@"The Mighty Yeet"));


// start SW
Stopwatch sw = new Stopwatch();
sw.Start();

// initialise
var cipher = new VignereCipher();
var breaker = new VignereBreaker();

// get text to work with
string text = Utilities.CipherFormat("YOHAP IEVFW WIZBU NWVGJ TMZKY FTNII URDGV IAIRT TNAIJ JDOCI JCZWM JYJII QEOHV WANYZ SGHSR GOPHK MEICK JTCOK IRRVZ YEYWJ HOQSI JDDBK MEWWE IIIUF KTCSS TOFTF ZNYPP NSGSJ XBJRP NCVBE TTNSV MORMF ZCJIC ITCWE PIRCL QDFBF BAIMK MIIUR GOPHZ YAIRZ KIIRZ YESHI JMZZP ZNGWB JLTHY FTDHT TUGRY FVZPV JNRFZ YTZBS DAIMF SEDBD DHJIJ JHJZU DOPFT QADAK MAOHY JCCOI FCOSI NSOWT XOAHY JTTDV HAIPV ZSZRK TIYSE YIAMK MENCL WCZOJ YHZHP UERFZ YEMKV MOGRZ STCSD FNNWF SSZSD XTJAV YOWSU NVDBR YIJBE TTNQZ JNXSR SDRWK MOPHD ZCCGK WOIUV WEQWU JNXSF KAGWE PBZHN JEIGF REJBV NNHMY TUNSY TLYOE ITCSP TUIUD FNDGC JSDKZ QLICK JNOSI YADBF WCJCG JRVHV BIOVR SYAII YHZFZ SVZGK NGVHZ TNNWY FVZOC WEVRP JXKFV XSZRD DCJBJ YEMBR YIJBR YTCSG WONDV HTJTR XCVBU FLYSI FIGWE LMTQR RPVWX SFJFJ YAOSX TVZFE TRVBU NTCCL LHOHY FTTCL ZNYSI XTJCU FNYOX WEZRN NTCAV BHTMF ZWJIC IWVBK YOMSF UEIHY JCVGV BHZBZ MAQSJ TMPQY YOGCJ JAIRN JHVJV SOOVZ SGOCX FIITI TMDHZ HAIBF YUIRV WSOOE IIFBF BTCOK RADGZ JHVGS JEIDI JSNWE LFJFW ZROVV WIIJV XTDUR YIJBR SDDHZ XCGSR WTCOK XHZKR XDZSG QYYWJ YRZGJ JDWMK MERVF QEDBT NDZBK XHZZF AENHY JLDPI FRTOE IWJIC IDJOE DTCWE LTJDI TTZQK NTCCN JVZFJ MEDGD JRZZP FSZFM FNOCW YHZSJ YAOSR SDNII JLTAP XTVHL XANDI JSZBK TWISI LIQSJ LRZOK JRRSZ LHOHF RYQWV BSVBU BINVV XWCWC JINZV XCGSR WLTHI JSKOJ XEYVV XEZAJ SOOHF MAQST FUNSU FNTRR RABSR SDZJV SIAVV BANWE YEIRZ SGOCJ YEVZW WOHAV MINIE YIHSC DDZOK MFJFV XTVZC JDOVR YPGOE MECOJ FLMSR IYKOZ ITCSG WIXSW TRCWJ RINRV JDNOE IIYCE TTNSV FNTFV FSJBK TCJBK NNPSK TPJYV FNYDI TBZOK BHVHD ZSOGL WEGMS JAMCL YIIST FSZWD ZSOWE XINHK MAOMF ZBMWE LAAWE FLCOC YTJMF ZRDBM JSOWX FTDCE XAIRC JTCWD WENHZ SPZOT JLZHL XNJHZ SVDHV LONGZ UAOHY NSXFZ YIXOC YIHSP TUMGZ SFMWV SDNVZ URJUV WS");

Console.WriteLine(cipher.Decrypt(text, new StringKey("FAVOR")));

// decrypt
var key = breaker.Break(text);

string plainText = cipher.Decrypt(text, key);

Console.WriteLine(key);
Console.WriteLine(plainText);
Console.WriteLine();

//FileOutput.JSONWriter.WriteToFile(outputPath, text, key.ToString(), cipher.Decrypt(text, key), "Substitution");

Console.WriteLine(sw.ElapsedMilliseconds);