package main

import "fmt"

const ct = `DEUQJVE IJU UVTSOGE DJUAPXETB, ISTQET UEENU VP ISXE ISD XETB MJVVME JOFMWEOAE PO VIE QPMJAE JOXEUVJGSVJPO SV VISV UVSGE, SOD NB JOXEUVJGSVJPO PF MPASM FJMEU UIPYU VISV VIE POMB SAVJXJVB JO VIE VYP NPOVIU FPMMPYJOG VIE DESVI YETE MEVVETU EZAISOGED HEVYEEO NSJUJE, TPGETU, ISTQET SOD YIJVE. TPGETU APOVJOWED VP VTB VP RWJEVEO VIE FWUU YIJME NSJUJE, JOATESUJOGMB SOZJPWU SHPWV IET QTEAJPWU MJHTSTB, YPTLED ISTD VP GEV VIEN SMM VP VSLE IET APOAETOU UETJPWUMB. JO VIE EOD NSJUJE UEENU VP ISXE MPUV QSVJEOAE SOD VP ISXE APNNJUUJPOED IET PYO JOXEUVJGSVJPO, MED HB VIE FSNPWU QJOLETVPO DEVEAVJXE SGEOAB. J SN OPV UWTE YIB UIE AIPUE VIEN, EUQEAJSMMB GJXEO VIE APUV, HWV JV NSB ISXE TEMSVED VP VIEJT TPGWEU GSMMETB, S OSVJPOSM DSVSHSUE YIJAI APOVSJOED QIPVPU SOD DEUATJQVJPOU PF S MSTGE OWNHET PF LOPYO SOD UWUQEAVED ATJNJOSMU. JV YSU VIE FJTUV PF JVU LJOD, SOD NSJUJE NSB ISXE IPQED VISV JV YPWMD TEXESM VIE JDEOVJVB PF IET JOVETMPQET. VIE AWTTEOV MJHTSTJSO SV VIE NSOUJPO LJODMB GSXE NE SAAEUU VP NSJUJE’U QTJXSVE TEAPTDU, S UETJEU PF DJSTJEU SOD MEVVETU, NSOB PF VIEN EOATBQVED, VISV YETE UVPTED JO VIE PFFJAE HEIJOD VIE FJTEQMSAE JO VIE MJHTSTB. J SN GTSDWSMMB YPTLJOG VITPWGI VIEN SMM, PT SV MESUV VIE POEU VISV UEEN VP HE TEMSVED VP VIJU ASUE, SOD YJMM QPUV SOBVIJOG TEMEXSOV. FPT UVSTVETU, IETE JU VIE TEQPTV FTPN VIE QJOLETVPOU SGEOV SUUJGOED VP VIE PTJGJOSM EORWJTB. J ISXEO’V ISD S AISOAE VP ATSAL VIE AJQIET BEV UP J DPO’V LOPY JF VIE TPGWEU GSMMETB QMSBED S TPME JO VIEJT JOXEUVJGSVJPOU, HWV QETISQU BPW ASO AIEAL VISV FPT NE. S RWJAL JOUQEAVJPO UIPYU VISV VIE MEVVET FTERWEOAJEU NSVAI VIE WUWSM DJUVTJHWVJPO QTEVVB AMPUEMB, UWGGEUVJOG VISV VIJU YSU OPV EOATBQVED WUJOG S UWHUVJVWVJPO AJQIET, UP BPW YJMM OEED VP WUE S DJFFETEOV SQQTPSAI VP ATSAL JV. GPPD MWAL, ISTTB`

const key = "SHADEFGIJ LMNOPQRTUVWXYZB "

func main() {
	sub := make(map[byte]byte)
	for i := byte(0); i < 26; i++ {
		if key[i] != ' ' {
			sub[key[i]] = 'A' + i
		}
	}

	pt := []byte(ct)
	for i := range pt {
		p, ok := sub[pt[i]]
		if ok {
			pt[i] = p
		} else if 'A' <= pt[i] && pt[i] <= 'Z' {
			panic("no good")
		}
	}
	fmt.Printf("%s\n", pt)
}
